---
driver:
  name: vagrant

  network:
  - ["forwarded_port", {guest: 80, host: 8000}]

  customize:
    memory: 2048

  synced_folders:
    - ["data/%{instance_name}", "/opt/instance_data"]

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.12.0

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: recipe[apache-site::default]
    attributes:
